### ISSUE TITLE
Skill having trouble finding "action_map.json" file.

### ISSUE THREAD

**Issue by thejoker030** [TomerFi/alexa_skill_ask_my_pc#2]
First of all, thank you so much for this!  I'm just having one little hiccup.  I've followed your instructions to a tee, and I was able to establish a connection with the Alexa skill.  If I test the skill with "start computer", I get the proper output.  However, anytime I try to do anything that references the "action_map.json" in the "C:\Alexa Computer Control\Apache Tomcat Server\apache-tomcat-9.0.5\webapps\ROOT\WEB-INF\conf_files" directory, I get an error in the log.  

This is the heading in my error log:

_2018-03-06 15:35:10 ERROR error:205 - C:\Alexa%20Computer%20Control\Apache%20Tomcat%20Server\apache-tomcat-9.0.5\webapps\ROOT\WEB-INF\conf_files\action_map.json (The system cannot find the path specified)

java.io.FileNotFoundException: C:\Alexa%20Computer%20Control\Apache%20Tomcat%20Server\apache-tomcat-9.0.5\webapps\ROOT\WEB-INF\conf_files\action_map.json (The system cannot find the path specified)"_

It just appears the it is mapped wrong somewhere.  I have double checked all of my Env. variables, and all files are where they should be.  Like I said, I have the skill working so I know 99% is OK.  It just won't access the "action_map.json" file.  

Any help would be greatly appreciated!  I'm extremely excited to get this working.  I'm so close.  :)   Thank you again!

Mike

**Comment by TomerFi** [comment]
I'm very sorry for the delayed response,
I haven't been following this repository for too long.
I just marked it as not maintained,
Please consider using [this solution](https://github.com/TomerFi/smathhome_computer_mqtt_client) instead.
